test
DianaSvetlova/HtmlCssJavaScript pull request #10
Opened 2024-12-24 18:12 UTC by DianaSvetlova

2024-12-27 08:00 UTC, DianaSvetlova commented
Затрачено 2 ч 40 мин (за 3 захода)
И всё равно осталось миллион вопросов, как можно было сделать по-другому/правильно))

2024-12-30 11:05 UTC, mhasilau requested changes

2024-12-30 11:05 UTC, mhasilau commented on test1/index.html
> +        <table class="table">
надо было не табличную верстку

2024-12-30 11:05 UTC, mhasilau commented on test1/index.html
> +                <td class="vk"><img
не используем инлайн стили. это про везде

2024-12-30 11:05 UTC, mhasilau commented on test1/index.html
> +                <tr>
тут друзья разъехались

2024-12-30 11:05 UTC, mhasilau commented on test1/index.html
> +            <table>
тут еще и не одна таблица....

2025-02-18 18:13 UTC, merged